import type { CustomerId, TechnicalTenantId } from '../stageA/partyAccount';
import { buildCommercialLifecycle, type LifecycleEvidence, type LifecycleStageId } from './commercialLifecycle';
import { buildTrustPosture, type TrustPostureInput } from './trustPosture';
import type { Customer360Summary, MappingState } from './customer360';
import { buildFinanceWorkspaceSummary, type FinanceWorkspaceSummary } from './financeWorkspace';
import { buildAiFinOpsSummary } from './aiFinOps';

export interface SyntheticScenario extends Customer360Summary { readonly demoCase: string; readonly organisation: string | null; readonly legalEntity: string | null; readonly billingAccount: string | null; readonly technicalTenantId: TechnicalTenantId | null; readonly mappingState: MappingState; readonly summary: string; }
const full: Partial<Record<LifecycleStageId, LifecycleEvidence>> = Object.fromEntries(['customer','organisation','legal_entity','billing_account','contract_quote','acceptance','order','subscription','entitlement','provisioning','usage','rating','charge','invoice','payment','allocation','reconciliation','settlement','accounting'].map(id => [id, { status: 'COMPLETED', sourceIds: [`synthetic-${id}`], detail: 'Synthetic demonstration record.' }])) as Partial<Record<LifecycleStageId, LifecycleEvidence>>;
const completeTrust: TrustPostureInput = Object.fromEntries(['organisation','legal_entity','contract','policy','identity','credential','data_classification','provider_approval','region_approval','security','budget','audit'].map(id => [id, { state: 'VERIFIED', sourceReference: `synthetic-${id}`, detail: 'Synthetic demonstration evidence.' }])) as TrustPostureInput;
function scenario(input: { key: string; name: string; demoCase: string; summary: string; mappingState?: MappingState; tenant?: string; evidence: Partial<Record<LifecycleStageId, LifecycleEvidence>>; trust?: TrustPostureInput; counts?: Partial<Customer360Summary['counts']>; finopsState?: 'WITHIN_BUDGET'|'WARNING'|'EXCEEDED'|'UNKNOWN'; providerCost?: number|null; customerCharge?: number|null; budget?: number|null; currency?: string; organisation?: string|null; legalEntity?: string|null; billingAccount?: string|null }): SyntheticScenario {
  const counts = { contracts: 0, contractVersions: 0, quotes: 0, quoteVersions: 0, acceptances: 0, orders: 0, orderVersions: 0, subscriptions: 0, subscriptionVersions: 0, entitlements: 0, usageEvents: 0, ratings: 0, charges: 0, invoices: 0, payments: 0, allocations: 0, credits: 0, refunds: 0, reconciliationBatches: 0, settlements: 0, accountingRequests: 0, ...input.counts };
  return Object.freeze({ customerId: `demo-customer-${input.key}` as CustomerId, customerName: input.name, organisationNames: Object.freeze(input.organisation ? [input.organisation] : []), legalEntityNames: Object.freeze(input.legalEntity ? [input.legalEntity] : []), billingAccountNames: Object.freeze(input.billingAccount ? [input.billingAccount] : []), technicalRelationships: Object.freeze(input.tenant ? [{ tenantId: input.tenant as TechnicalTenantId, mappingState: input.mappingState ?? 'matched', note: input.mappingState === 'ambiguous' ? 'More than one candidate mapping; no selection made.' : 'Synthetic mapping evidence is explicitly supplied by this fixture.' }] : []), identityWarning: 'COMMERCIAL_IDENTITY_SEPARATE_FROM_TECHNICAL_TENANT', counts: Object.freeze(counts), operations: Object.freeze({ users: [], applications: [], apiConsumers: [], agents: [], credentials: [], policies: [], provisioningStates: [] }), lifecycle: buildCommercialLifecycle(input.evidence), trust: buildTrustPosture(input.trust ?? {}), finops: buildAiFinOpsSummary({ dimensions: { customerId: `demo-customer-${input.key}`, organisationId: input.organisation ? `demo-org-${input.key}` : null, department: null, costCentre: null, userId: null, applicationId: input.tenant ? `demo-app-${input.key}` : null, agentId: null, apiConsumerId: null, providerId: input.providerCost == null ? null : 'synthetic-provider', modelId: input.providerCost == null ? null : 'synthetic-model' }, usageQuantity: input.providerCost == null ? null : 1200, usageUnit: input.providerCost == null ? null : 'request', measures: [{ currency: input.currency ?? 'ZAR', providerCost: input.providerCost ?? null, customerCharge: input.customerCharge ?? null, budget: input.budget ?? null, threshold: input.budget == null ? null : input.budget * 0.8, budgetState: input.finopsState ?? 'UNKNOWN' }], evidenceState: 'SYNTHETIC' }), provenance: 'DOMAIN_SOURCE_PROJECTION', demoCase: input.demoCase, organisation: input.organisation ?? null, legalEntity: input.legalEntity ?? null, billingAccount: input.billingAccount ?? null, technicalTenantId: (input.tenant ?? null) as TechnicalTenantId | null, mappingState: input.mappingState ?? (input.tenant ? 'matched' : 'unknown'), summary: input.summary });
}
export const stageFSyntheticScenarios: readonly SyntheticScenario[] = Object.freeze([
  scenario({ key: 'a', name: 'Synthetic Customer A', demoCase: 'Complete lifecycle', summary: 'Synthetic end-to-end commercial path with linked lineage.', tenant: 'demo-tenant-a', evidence: full, trust: completeTrust, counts: { contracts: 1, contractVersions: 1, quotes: 1, quoteVersions: 1, acceptances: 1, orders: 1, orderVersions: 1, subscriptions: 1, subscriptionVersions: 1, entitlements: 1, usageEvents: 3, ratings: 3, charges: 3, invoices: 1, payments: 1, allocations: 1, reconciliationBatches: 1, settlements: 1, accountingRequests: 1 }, organisation: 'Synthetic Organisation A', legalEntity: 'Synthetic Legal Entity A', billingAccount: 'Synthetic Billing Account A', providerCost: 42, customerCharge: 60, budget: 100, finopsState: 'WITHIN_BUDGET' }),
  scenario({ key: 'b', name: 'Synthetic Customer B', demoCase: 'Authority pending', summary: 'Contract/quote authority is pending; downstream stages remain not started.', evidence: { customer: { status: 'COMPLETED', sourceIds: ['demo-customer-b'] }, organisation: { status: 'COMPLETED', sourceIds: ['demo-org-b'] }, legal_entity: { status: 'COMPLETED', sourceIds: ['demo-entity-b'] }, billing_account: { status: 'COMPLETED', sourceIds: ['demo-account-b'] }, contract_quote: { status: 'PENDING', sourceIds: ['demo-quote-b'], detail: 'Awaiting customer decision.' }, acceptance: { status: 'PENDING', sourceIds: [] }, order: { status: 'NOT_STARTED', sourceIds: [] }, subscription: { status: 'NOT_STARTED', sourceIds: [] } }, counts: { quotes: 1 }, organisation: 'Synthetic Organisation B', legalEntity: 'Synthetic Legal Entity B', billingAccount: 'Synthetic Billing Account B' }),
  scenario({ key: 'c', name: 'Synthetic Customer C', demoCase: 'Ambiguous tenant mapping', summary: 'Technical tenant exists in this fixture; commercial mapping is ambiguous and is not resolved.', mappingState: 'ambiguous', tenant: 'demo-tenant-c', evidence: { customer: { status: 'UNKNOWN', sourceIds: [] }, billing_account: { status: 'AMBIGUOUS', sourceIds: ['candidate-account-1','candidate-account-2'] } } }),
  scenario({ key: 'd', name: 'Synthetic Customer D', demoCase: 'Constrained entitlement', summary: 'Subscription is active; entitlement is suspended and provisioning is blocked.', tenant: 'demo-tenant-d', evidence: { ...full, entitlement: { status: 'SUSPENDED', sourceIds: ['demo-entitlement-d'] }, provisioning: { status: 'BLOCKED', sourceIds: ['demo-entitlement-d'], detail: 'Synthetic policy decision.' } }, counts: { subscriptions: 1, entitlements: 1 }, organisation: 'Synthetic Organisation D', legalEntity: 'Synthetic Legal Entity D', billingAccount: 'Synthetic Billing Account D' }),
  scenario({ key: 'e', name: 'Synthetic Customer E', demoCase: 'Financial exception', summary: 'Synthetic invoice/payment present with unresolved reconciliation exception.', tenant: 'demo-tenant-e', evidence: { ...full, reconciliation: { status: 'REQUIRES_REVIEW', sourceIds: ['demo-recon-e'] }, settlement: { status: 'BLOCKED', sourceIds: ['demo-recon-e'] }, accounting: { status: 'PENDING', sourceIds: [] } }, counts: { invoices: 1, payments: 1, allocations: 1, reconciliationBatches: 1 }, organisation: 'Synthetic Organisation E', legalEntity: 'Synthetic Legal Entity E', billingAccount: 'Synthetic Billing Account E' }),
  scenario({ key: 'f', name: 'Synthetic Customer F', demoCase: 'AI budget warning', summary: 'Synthetic AI usage is approaching the configured budget threshold.', tenant: 'demo-tenant-f', evidence: { usage: { status: 'COMPLETED', sourceIds: ['demo-usage-f'] }, rating: { status: 'COMPLETED', sourceIds: ['demo-rating-f'] }, charge: { status: 'COMPLETED', sourceIds: ['demo-charge-f'] } }, counts: { usageEvents: 15, ratings: 15, charges: 15 }, providerCost: 790, customerCharge: 960, budget: 1000, finopsState: 'WARNING', currency: 'USD', organisation: 'Synthetic Organisation F', legalEntity: 'Synthetic Legal Entity F', billingAccount: 'Synthetic Billing Account F' }),
]);
export const stageFFinanceDemoSummary: FinanceWorkspaceSummary = buildFinanceWorkspaceSummary({ customerCount: stageFSyntheticScenarios.length, openQuoteCount: 1, activeSubscriptionCount: 2, chargeCount: 18, invoiceCount: 2, paymentCount: 2, reconciliationExceptionCount: 1, accountingPendingCount: 1, totalsByCurrency: [{ currency: 'ZAR', invoiced: 1250, captured: 900, allocated: 900 }, { currency: 'USD', invoiced: 0, captured: 0, allocated: 0 }], evidenceState: 'SYNTHETIC', lifecycle: buildCommercialLifecycle(full) });
