import React,{useEffect,useMemo,useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,BarChart,Bar} from 'recharts';
import {ArrowUpRight,Building2,ChevronRight,CircleDollarSign,Code2,ExternalLink,FileKey2,Layers3,PackageCheck,RefreshCw,Rocket,ShieldCheck,Users} from 'lucide-react';
import type {Customer,LicensingPlanTemplate} from '../types';
import type {NavTabId} from './Sidebar';

type Registration={id:string;email:string;createdAt:string;status:string;planId:string;tenantId:string;customerName:string};
export const SaasGrowthView:React.FC<{customers:Customer[];plans:LicensingPlanTemplate[];onNavigate:(tab:NavTabId)=>void}>=({customers,plans,onNavigate})=>{
 const [registrations,setRegistrations]=useState<Registration[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const API=`${import.meta.env.BASE_URL}api/v1`;
 const refresh=async()=>{setBusy(true);try{const r=await fetch(`${API}/admin/registrations`);if(!r.ok)throw new Error('Registration records are unavailable.');setRegistrations(await r.json());setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{void refresh();},[]);
 const growth=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const name=d.toLocaleString('en',{month:'short'});return{name,tenants:customers.filter(c=>new Date(c.createdAt).getMonth()===d.getMonth()&&new Date(c.createdAt).getFullYear()===d.getFullYear()).length};}),[customers]);
 const hierarchy=useMemo(()=>customers.reduce((acc,c)=>{const key=c.orgRole||'direct_client';acc[key]=(acc[key]||0)+1;return acc;},{} as Record<string,number>),[customers]);
 const activate=async(id:string,status:'contacted'|'closed')=>{const r=await fetch(`${API}/admin/registrations/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!r.ok){setError('Could not update registration status.');return;}await refresh();};
 const card='rounded-2xl border border-[#242b3a] bg-[#121722]';
 return <div className="space-y-5 text-slate-100"><header className="relative overflow-hidden rounded-3xl border border-violet-300/15 bg-gradient-to-br from-[#271f48] via-[#171d30] to-[#10151e] p-6 md:p-8"><div className="absolute -right-12 -top-24 h-80 w-80 rounded-full bg-violet-400/10 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><span className="inline-flex items-center gap-2 rounded-full border border-violet-200/20 bg-violet-200/10 px-3 py-1.5 text-[10px] uppercase tracking-[.18em] text-violet-100"><Rocket size={14}/> SaaS growth engine</span><h1 className="mt-4 text-3xl font-semibold md:text-4xl">From first signup to enterprise fleet.</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Control product packaging, self-serve onboarding, corporate account structures and the public ALTIL API surface from one place.</p></div><div className="flex flex-wrap gap-2"><a href="/register" target="_blank" rel="noreferrer" className="rounded-xl bg-violet-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Preview signup <ExternalLink size={14} className="ml-2 inline"/></a><button onClick={()=>void refresh()} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-300"><RefreshCw size={14} className="mr-2 inline"/>Refresh</button></div></div></header>
 {error&&<div className="rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-200">{error}</div>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Tenant workspaces',value:customers.length,detail:`${customers.filter(c=>c.status==='trial').length} in trial`,icon:Building2},{label:'Published packages',value:plans.filter(p=>p.isPublished).length,detail:'Live on self-service signup',icon:PackageCheck},{label:'Corporate hierarchy',value:Object.values(hierarchy).reduce<number>((a,b)=>a+Number(b),0),detail:`${hierarchy.parent_owner||0} parent organizations · ${hierarchy.subsidiary||0} subsidiaries`,icon:Layers3},{label:'New registrations',value:registrations.filter(r=>r.status==='trial_active').length,detail:'Self-service accounts provisioned',icon:Users}].map(k=>{const Icon=k.icon;return <div className={`${card} p-4`} key={k.label}><div className="flex justify-between text-xs text-slate-400"><span>{k.label}</span><Icon size={17} className="text-violet-200"/></div><div className="mt-3 text-3xl font-semibold">{k.value}</div><div className="mt-1 text-xs text-slate-500">{k.detail}</div></div>})}</section>
 <section className="grid gap-4 xl:grid-cols-[1.3fr_1fr]"><div className={`${card} p-5`}><h2 className="font-semibold">Workspace momentum</h2><p className="mt-1 text-xs text-slate-500">New tenants created each month</p><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><AreaChart data={growth}><defs><linearGradient id="signupGrowth" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c4b5fd" stopOpacity={.3}/><stop offset="100%" stopColor="#c4b5fd" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#282f3d" vertical={false}/><XAxis dataKey="name" tick={{fill:'#788296',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#788296',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#101620',border:'1px solid #30384a',borderRadius:12}}/><Area type="monotone" dataKey="tenants" stroke="#c4b5fd" fill="url(#signupGrowth)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className={`${card} p-5`}><h2 className="font-semibold">Organization composition</h2><p className="mt-1 text-xs text-slate-500">One hierarchy, many account shapes</p><div className="mt-3 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Parent',value:hierarchy.parent_owner||0},{name:'Subsidiary',value:hierarchy.subsidiary||0},{name:'Partner',value:hierarchy.partner_reseller||0},{name:'Client',value:hierarchy.direct_client||0}]}><CartesianGrid stroke="#282f3d" vertical={false}/><XAxis dataKey="name" tick={{fill:'#788296',fontSize:10}} axisLine={false} tickLine={false}/><YAxis hide/><Tooltip contentStyle={{background:'#101620',border:'1px solid #30384a',borderRadius:12}}/><Bar dataKey="value" fill="#a78bfa" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></section>
 <section className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><div className={`${card} overflow-hidden`}><div className="flex items-center justify-between border-b border-white/5 p-4"><div><h2 className="font-semibold">Product catalogue</h2><p className="mt-1 text-xs text-slate-500">Packages published to the public registration site</p></div><button onClick={()=>onNavigate('tenant_licensing')} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Manage packages <ChevronRight size={13} className="ml-1 inline"/></button></div><div className="grid gap-3 p-4 md:grid-cols-2">{plans.filter(p=>p.isPublished).slice(0,6).map(p=><div key={p.id} className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="flex items-start justify-between"><div><b className="text-sm">{p.name}</b><div className="mt-1 text-[10px] text-slate-500">{p.licenseScope||'Application'} license · {p.billingCycle}</div></div><PackageCheck size={16} className="text-violet-200"/></div><div className="mt-4 text-2xl font-semibold">{p.currency} {p.basePrice.toLocaleString()}<span className="ml-1 text-xs font-normal text-slate-500">/{p.billingCycle==='monthly'?'mo':p.billingCycle}</span></div><div className="mt-2 text-xs text-slate-400">{p.includedTransactions.toLocaleString()} included requests · {p.gracePeriodDays} day grace</div><div className="mt-3 flex flex-wrap gap-1">{p.features.slice(0,3).map(f=><span key={f} className="rounded-full bg-white/5 px-2 py-1 text-[9px] text-slate-400">{f}</span>)}</div></div>)}</div></div>
 <div className={`${card} p-5`}><div className="flex items-center gap-2"><CircleDollarSign size={18} className="text-emerald-200"/><h2 className="font-semibold">Onboarding pathways</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Individuals and companies can self-register. Introsoft can also create parent tenants, subsidiaries, reseller partners and client accounts.</p><div className="mt-5 space-y-2">{[['Tenant directory','Create and maintain client accounts','tenants'],['Organization tree','Build and inspect multi-level company structures','org_hierarchy'],['Licensing studio','Assign a package to each application','tenant_licensing'],['Billing desk','Draft, issue and reconcile invoices','billing_admin']].map(([title,sub,tab])=><button key={title} onClick={()=>onNavigate(tab as NavTabId)} className="flex w-full items-center gap-3 rounded-xl border border-white/5 bg-white/[.025] p-3 text-left hover:bg-white/[.06]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-300/10 text-violet-200"><ArrowUpRight size={15}/></span><span className="min-w-0 flex-1"><b className="block text-xs">{title}</b><small className="text-[10px] text-slate-500">{sub}</small></span><ChevronRight size={14} className="text-slate-600"/></button>)}</div><a href={`${import.meta.env.BASE_URL}api/v1/openapi.yaml`} className="mt-4 flex items-center gap-2 rounded-xl border border-cyan-300/15 bg-cyan-300/[.04] p-3 text-xs text-cyan-100"><Code2 size={15}/> Open API contract <FileKey2 size={14} className="ml-auto"/></a><p className="mt-2 text-[10px] text-slate-600">Swagger / OpenAPI 3.1 · versioned · tenant-scoped keys</p></div></section>
 <section className={`${card} overflow-hidden`}><div className="flex items-center justify-between border-b border-white/5 p-4"><div><h2 className="font-semibold">Self-service registration feed</h2><p className="mt-1 text-xs text-slate-500">New workspaces provisioned from the Introsoft signup website</p></div><button onClick={()=>void refresh()} disabled={busy} className="text-xs text-slate-400"><RefreshCw size={13} className={`mr-1 inline ${busy?'animate-spin':''}`}/>Update</button></div><div className="overflow-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-white/[.02] text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Workspace','Owner email','Package','Created','Status','Manage'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{registrations.slice(0,15).map(r=><tr key={r.id} className="border-t border-white/5"><td className="px-4 py-3 font-medium">{r.customerName}</td><td className="px-4 py-3 text-slate-400">{r.email}</td><td className="px-4 py-3 text-slate-400">{plans.find(p=>p.id===r.planId)?.name||r.planId}</td><td className="px-4 py-3 text-slate-400">{new Date(r.createdAt).toLocaleString()}</td><td className="px-4 py-3 capitalize text-emerald-200">{r.status.replace('_',' ')}</td><td className="px-4 py-3"><button onClick={()=>onNavigate('tenant_360')} className="text-violet-200">Open account</button></td></tr>)}</tbody></table>{!registrations.length&&<div className="p-8 text-center text-xs text-slate-500">No self-service registrations yet.</div>}</div></section>
 <div className="flex items-center justify-between text-[10px] text-slate-600"><span><ShieldCheck size={12} className="mr-1 inline text-emerald-300"/>Multi-tenant boundaries enforced by the account and gateway layers</span><span>{customers.length} accounts · {plans.length} configured packages</span></div>
 </div>;
};

