import React from 'react';
import { AlertTriangle, ArrowDown, CircleDollarSign, ShieldCheck } from 'lucide-react';
import { stageFFinanceDemoSummary, stageFSyntheticScenarios, type SyntheticScenario } from '../commercial/stageF/syntheticData';
import { financeSections, type FinanceSectionId } from '../commercial/stageF/financeWorkspace';
import type { LifecycleNode } from '../commercial/stageF/commercialLifecycle';

const statusTone: Record<string, string> = { COMPLETED: 'text-emerald-300 border-emerald-300/20 bg-emerald-300/5', ACTIVE: 'text-emerald-300 border-emerald-300/20 bg-emerald-300/5', VERIFIED: 'text-emerald-300 border-emerald-300/20 bg-emerald-300/5', PENDING: 'text-amber-200 border-amber-300/20 bg-amber-300/5', AMBIGUOUS: 'text-amber-200 border-amber-300/20 bg-amber-300/5', REQUIRES_REVIEW: 'text-amber-200 border-amber-300/20 bg-amber-300/5', BLOCKED: 'text-rose-200 border-rose-300/20 bg-rose-300/5', UNKNOWN: 'text-slate-300 border-white/10 bg-white/[.03]', UNLINKED: 'text-slate-300 border-white/10 bg-white/[.03]', NOT_STARTED: 'text-slate-400 border-white/10 bg-white/[.02]', NOT_CONFIGURED: 'text-slate-400 border-white/10 bg-white/[.02]', EVIDENCE_REQUIRED: 'text-amber-200 border-amber-300/20 bg-amber-300/5', SUSPENDED: 'text-rose-200 border-rose-300/20 bg-rose-300/5', NOT_AUTHORIZED: 'text-rose-200 border-rose-300/20 bg-rose-300/5' };
const Badge = ({ value }: { value: string; key?: React.Key }) => <span className={`inline-flex rounded-full border px-2 py-1 text-[9px] font-semibold uppercase tracking-wider ${statusTone[value] || statusTone.UNKNOWN}`}>{value.replaceAll('_', ' ')}</span>;
const Card = ({ children, className = '' }: { children: React.ReactNode; className?: string; key?: React.Key }) => <section className={`rounded-2xl border border-white/[.08] bg-[#121720] p-4 ${className}`}>{children}</section>;

export function LifecycleList({ nodes }: { nodes: readonly LifecycleNode[] }) { return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{nodes.map((node, index) => <div key={node.id} className="relative rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium">{index + 1}. {node.label}</span><Badge value={node.status}/></div><p className="mt-2 text-[10px] leading-4 text-slate-500">{node.detail}</p>{node.sourceIds.length > 0 && <p className="mt-1 truncate font-mono text-[9px] text-slate-600">{node.sourceIds.join(' · ')}</p>}</div>)}</div>; }

export const StageFFinanceView: React.FC = () => {
  const [section, setSection] = React.useState<FinanceSectionId>('overview');
  const [selectedId, setSelectedId] = React.useState(stageFSyntheticScenarios[0].customerId as string);
  const selected = stageFSyntheticScenarios.find(item => item.customerId === selectedId) || stageFSyntheticScenarios[0];
  return <main className="space-y-5 pb-12 text-slate-100">
    <header className="rounded-3xl border border-cyan-200/10 bg-gradient-to-br from-[#123344] via-[#17202b] to-[#10141d] p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-cyan-100"><CircleDollarSign size={14}/>Finance · Commercial lifecycle</span><h1 className="mt-3 text-3xl font-semibold">Finance workspace</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">One contextual view across parties, authority, service, usage and financial lineage. Existing finance screens remain available in the sidebar.</p></div><span className="rounded-full border border-amber-200/20 bg-amber-100/5 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider text-amber-100">Synthetic local demonstration</span></div></header>
    <nav className="flex gap-2 overflow-x-auto border-b border-white/10 pb-3" aria-label="Finance workspace sections">{financeSections.map(item => <button key={item.id} type="button" onClick={() => setSection(item.id)} aria-pressed={section === item.id} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs ${section === item.id ? 'bg-cyan-200/10 text-cyan-100' : 'text-slate-400 hover:bg-white/5'}`}>{item.label}</button>)}</nav>
    <div className="flex flex-wrap items-center gap-3"><label className="text-xs text-slate-400">Synthetic customer scenario<select aria-label="Select synthetic customer scenario" value={selectedId} onChange={event => setSelectedId(event.target.value)} className="ml-2 rounded-lg border border-white/10 bg-[#111720] px-3 py-2 text-xs text-white">{stageFSyntheticScenarios.map(item => <option key={item.customerId} value={item.customerId}>{item.customerName} · {item.demoCase}</option>)}</select></label><span className="text-[10px] text-slate-600">Values are fixture data; no API, database, or production facts are read.</span></div>
    {section === 'overview' && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Customers', stageFFinanceDemoSummary.customerCount], ['Open quotes', stageFFinanceDemoSummary.openQuoteCount], ['Invoices', stageFFinanceDemoSummary.invoiceCount], ['Reconciliation exceptions', stageFFinanceDemoSummary.reconciliationExceptionCount]].map(([label, value]) => <Card key={label}><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div><div className="mt-1 text-[9px] text-amber-100/70">Synthetic demonstration</div></Card>)}</div><Card><h2 className="mb-3 text-sm font-semibold">Commercial lifecycle</h2><LifecycleList nodes={selected.lifecycle}/></Card></>}
    {section === 'customers_accounts' && <><CustomerScenarioHeader scenario={selected}/><Card><h2 className="text-sm font-semibold">Commercial and technical identity</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded-xl bg-black/15 p-3"><div className="text-[10px] uppercase text-slate-500">Commercial customer</div><b className="mt-1 block text-sm">{selected.customerName}</b><small className="font-mono text-slate-500">{selected.customerId}</small></div><div className="rounded-xl bg-black/15 p-3"><div className="text-[10px] uppercase text-slate-500">Technical tenant</div><b className="mt-1 block text-sm">{selected.technicalTenantId ?? 'Not supplied'}</b><div className="mt-2"><Badge value={selected.mappingState.toUpperCase()}/></div></div></div><p className="mt-3 text-[10px] text-amber-100/80">A tenant is a technical security scope. It does not become the commercial customer by name or presence.</p></Card><div className="grid gap-3 lg:grid-cols-2"><Card><h2 className="mb-3 text-sm font-semibold">Trust / control posture</h2><div className="grid gap-2 sm:grid-cols-2">{selected.trust.map(item => <div key={item.id} className="flex items-center justify-between gap-2 border-b border-white/5 py-2"><span className="text-[10px] text-slate-400">{item.label}</span><Badge value={item.state}/></div>)}</div></Card><Card><h2 className="text-sm font-semibold">AI FinOps</h2><p className="mt-2 text-[10px] text-slate-500">Synthetic dimensions: customer, organisation, application, provider and model.</p>{selected.finops.measures.map((measure, index) => <div key={`${measure.currency}-${index}`} className="mt-3 grid grid-cols-2 gap-2 text-xs"><span className="text-slate-400">Provider cost</span><b>{measure.providerCost == null ? 'UNKNOWN' : `${measure.currency} ${measure.providerCost.toFixed(2)}`}</b><span className="text-slate-400">Customer charge</span><b>{measure.customerCharge == null ? 'UNKNOWN' : `${measure.currency} ${measure.customerCharge.toFixed(2)}`}</b><span className="text-slate-400">Budget state</span><Badge value={measure.budgetState}/></div>)}</Card></div></>}
    {section !== 'overview' && section !== 'customers_accounts' && <><CustomerScenarioHeader scenario={selected}/><section className="grid gap-3 md:grid-cols-2">{sectionCards(section, selected).map(card => <Card key={card.title}><h2 className="text-sm font-semibold">{card.title}</h2><p className="mt-2 text-xs leading-5 text-slate-400">{card.description}</p><div className="mt-3 flex flex-wrap gap-2">{card.states.map(state => <Badge key={state} value={state}/>)}</div></Card>)}</section></>}
    <Card className="flex items-start gap-3"><AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-200"/><p className="text-[10px] leading-5 text-slate-400">This workspace is a local presentation prototype. It does not create, issue, approve, collect, reconcile, or post financial records. Unknown and missing relationships stay visible as unknown.</p></Card>
  </main>;
};
function CustomerScenarioHeader({ scenario }: { scenario: SyntheticScenario }) { return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider text-slate-500">Selected synthetic case · {scenario.demoCase}</div><h2 className="mt-1 text-lg font-semibold">{scenario.customerName}</h2><p className="mt-1 text-xs text-slate-400">{scenario.summary}</p></div><Badge value={scenario.mappingState.toUpperCase()}/></div></Card>; }
function sectionCards(section: FinanceSectionId, scenario: SyntheticScenario) {
  const bySection: Record<Exclude<FinanceSectionId, 'overview'|'customers_accounts'>, { title: string; description: string; states: string[] }[]> = {
    catalogue_pricing: [{ title: 'Catalogue & price snapshots', description: 'Product, price version, currency and effective date remain linked to source records.', states: ['UNKNOWN', 'EVIDENCE REQUIRED'] }],
    quotes_contracts: [{ title: 'Contract / quote authority', description: 'Both contract-first and quote-first authority paths are supported. The active path is supplied by explicit evidence.', states: [scenario.lifecycle.find(x => x.id === 'contract_quote')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'acceptance')?.status ?? 'UNKNOWN'] }],
    orders_subscriptions: [{ title: 'Order → subscription → entitlement', description: 'Recurring order lines, subscriptions, entitlements and provisioning decisions remain distinct objects.', states: [scenario.lifecycle.find(x => x.id === 'order')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'subscription')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'entitlement')?.status ?? 'UNKNOWN'] }],
    usage_charges: [{ title: 'AI FinOps', description: `${scenario.finops.measures[0]?.currency ?? 'Currency unknown'} · provider cost ${scenario.finops.measures[0]?.providerCost == null ? 'UNKNOWN' : scenario.finops.measures[0].providerCost.toFixed(2)} · customer charge ${scenario.finops.measures[0]?.customerCharge == null ? 'UNKNOWN' : scenario.finops.measures[0].customerCharge.toFixed(2)} · budget ${scenario.finops.measures[0]?.budget == null ? 'UNKNOWN' : scenario.finops.measures[0].budget.toFixed(2)}.`, states: [scenario.finops.evidenceState, scenario.finops.measures[0]?.budgetState ?? 'UNKNOWN'] }],
    invoices_payments_credits: [{ title: 'Invoice, payment and credit', description: 'Invoice balance, captured payment, allocation, credit note and cash refund remain separate concepts.', states: [scenario.lifecycle.find(x => x.id === 'invoice')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'payment')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'allocation')?.status ?? 'UNKNOWN'] }],
    reconciliation_accounting: [{ title: 'Reconciliation and accounting handoff', description: 'Reconciliation exceptions remain explicit. Journal requests are not represented as posted accounting entries.', states: [scenario.lifecycle.find(x => x.id === 'reconciliation')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'settlement')?.status ?? 'UNKNOWN', scenario.lifecycle.find(x => x.id === 'accounting')?.status ?? 'UNKNOWN'] }],
    reports: [{ title: 'Reports', description: 'Financial measures are grouped by transaction currency; this prototype does not convert or net currencies.', states: ['SYNTHETIC', ...scenario.finops.measures.map(x => x.currency)] }],
  };
  return bySection[section as Exclude<FinanceSectionId, 'overview'|'customers_accounts'>] || [];
}

export const Customer360CommercialPanel: React.FC<{ technicalTenantId: string }> = ({ technicalTenantId }) => <Card><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 text-amber-200" size={17}/><div><h3 className="text-sm font-semibold">Commercial relationship requires verification</h3><p className="mt-1 text-xs text-slate-400">Technical tenant <code className="font-mono text-slate-300">{technicalTenantId}</code> is shown as its own security scope. This screen has no verified Customer, Organisation, Legal Entity, Billing Account, or mapping feed, so commercial identity and lifecycle remain UNKNOWN.</p><p className="mt-2 text-[10px] text-slate-500">Tenant metadata, license, order, invoice, payment, and API key presence are not used to infer commercial authority.</p></div></div></Card>;

export const CustomerPortalCommercialNotice: React.FC<{ technicalTenantId: string }> = ({ technicalTenantId }) => <section className="rounded-xl border border-amber-200/15 bg-amber-100/[.03] p-4"><div className="flex items-center gap-2 text-sm font-medium"><ShieldCheck size={15} className="text-amber-200"/>Commercial account access</div><p className="mt-2 text-xs leading-5 text-slate-400">This portal is currently scoped to technical tenant <code className="font-mono text-slate-300">{technicalTenantId}</code>. A verified commercial account mapping and customer-owned view permission were not supplied to this local UI, so contracts, quotes, orders and cross-tenant financial records are not exposed here.</p><p className="mt-1 text-[10px] text-slate-500">Existing tenant billing and license panels remain compatibility views; they do not prove contract acceptance or subscription authority.</p></section>;
